### ISSUE TITLE
HWLoop relocation error

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-binutils-gdb#111]
Hi,

Using [this test](https://github.com/openhwgroup/corev-binutils-gdb/files/13588167/corev_rand_pulp_hwloop_exception_1743992155.S.gz) and 20231128 or 20231205 toolchain, the following error is produced:

> corev_rand_pulp_hwloop_exception_1743992155.S:428:(.text+0x614): relocation truncated to fit: R_RISCV_CVPCREL_URS1 against `hwloop1_end_stream1_id0'
> collect2: error: ld returned 1 exit status

Regards,
Pascal.

**Comment by amylaar** [comment]
There are 31 instructions inside the loop, and since the offset goes from the address of the cv.setupi to the end of the loop, the value to encode would be 32.  Yet cv.setup allows a maximum value of 31 to be encoded (0 is a constraint violation, and 1 an empty loop.  It would make sense to encode 32 as 0, but the manual says nothing about that, so the implementation can do whatever it wants with it).  Thus, gas / ld are correct in flagging this as an error.
I can conclude that this is either a compiler bug or a user error.

Can you submit the C code and the compilation options used to generate this assembly code?

I had a look at the code in the compiler that's supposed to prevent out-of-range cv.setupi end label references, and found some flaws.
ssh://git@github.com/embecosm/corev-gcc branch jwr-hwlp-mrg-20231117

Can you check if that fixes your case?  It also would be good to have the code as a regression test if confidentiality / copyright allows.

**Comment by pascalgouedo** [comment]
Hi @amylaar
Thanks for your analysis.
In fact this test was not generated by the compiler from C code but by a random generator for verification purpose.
We have this constraint of not having more than 30 instructions when using cv.setupi in the generator.
But some tests are then post-processed to add illegal instructions and so that's why sometimes it breaks the rule.

So no compiler pb there.

If the error message could be a bit more explicit it would help to avoid to falsely enter compiler bugs.

Best regards,
Pascal.

**Comment by pz9115** [comment]
It might a problem that gcc does not support long jump instructions.

See https://github.com/riscv-collab/riscv-gnu-toolchain/issues/1045

And it had fixed with this patch:

https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=71f906498ada9ec2780660b03bd6e27a93ad350c

I think you can try to apply this patch in gcc and see if it works.

**Comment by pascalgouedo** [comment]
Closing as not a toolchain problem.
