### ISSUE TITLE
Upgrade to version 1.0.0rc5.5

### ISSUE THREAD

**Issue by jeremybennett** [openhwgroup/corev-binutils-gdb#46]
The latest version makes some changes to the current work. See [specification draft 1.0.0rv5.5](https://github.com/riscv/riscv-code-size-reduction/releases/tag/v1.0.0-RC5.5).

**Comment by pz9115** [comment]
Proposal from specification change:
- [ ]  Remove zcmb extension, since the benefit is low, keep zcb extension only.
- [ ]  Add zcd extension  refer to compressed double-precision floating-point load/stores
- [ ] Zcf now limit on RV32 only
- [ ] Check zcb implyment and add them
- [ ] Check cm.jalt changes and update it

**Comment by abukharmeh** [comment]
CFI for Zcmp might need fixing, ref : https://github.com/riscv/riscv-code-size-reduction/issues/182

**Comment by pz9115** [comment]
New upgrade to version 1.0.0rc5.6:

See [specification draft 1.0.0rv5.6](https://github.com/riscv/riscv-code-size-reduction/releases/tag/v1.0.0-RC5.6).

- [ ] remove zcmpe extension

**Comment by tariqkurd-repo** [comment]
note the cm.jt/cm.jalt split has changed

**Comment by jeremybennett** [comment]
This is the subject of https://github.com/openhwgroup/corev-binutils-gdb/pull/65, currently under review

**Comment by jeremybennett** [comment]
#65 has now been merged, so this can be closed.
